version: "3"
services:
  my-vpbank:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/srcs
    environment:
      - REACT_APP_BACKEND_URL=http://192.168.8.101:9999
      - REACT_APP_ANOTHER_KEY=abcd