version: "3"
services:
  my-vpbank:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_BACKEND_URL=https://myvpb-test.vpbank.com.vn
        - REACT_APP_ANOTHER_KEY=production
        - REACT_APP_AZURE_CLIENT_ID=c023de9c-b2d0-4898-bf45-9c3e36141158
        - REACT_APP_AZURE_AUTHORITY=https://login.microsoftonline.com/ce81b2be-68d6-4005-9002-81c412e72061
        - REACT_APP_AZURE_REDIRECT_URI=http://localhost:8080/cms/login
    ports:
      - "8080:80"